// Vaisseaux jouables, vus de profil (nez à droite). Pixel art défini en texte.
// Les lignes sont dessinées au pixel fin (K = 2) : grande version 128×40 (64×20 logiques),
// petite version 60×22 (30×11 logiques). Une lettre = une couleur de la palette du modèle ;
// les tuyères sont les pixels « e » de la colonne de gauche (repérées automatiquement).

// Palette commune : coque (w > l > m > s > d), contour o, livrée a/b/A et p/q, verrière c/k/j/h/g.
const BASE = {
  o: '#141a2b',
  x: '#0c0f1a',
  d: '#3d4363',
  s: '#6c7392',
  m: '#a4aabd',
  l: '#d4d8df',
  w: '#f6f2e8',
  a: '#ea8a2e',
  b: '#a14c22',
  A: '#ffc070',
  p: '#d8443a',
  q: '#7e2230',
  y: '#ffe9a8',
  c: '#17223a',
  k: '#24508a',
  g: '#e8fbff',
  e: '#20283d',
  r: '#4d5472',
  n: '#535a7c',
  h: '#7fd0f5',
  j: '#3f86c8',
};

export const SHIP_MODELS = {
  // Zorgon Peterson Mandalay : long dard effilé, ailes arrière relevées en flèche, livrée blanche et orange.
  mandalay: {
    palette: { ...BASE },
    gear: [16, 40, 54],
    lights: [[6,  15,  '#ff4a4a',  0],  [17,  1,  '#eaffff',  0.55]],
    rows: [
      '................................................................................................................................',
      '................................................................................................................................',
      '...............................oooooooooooo.....................................................................................',
      '......................oooooooooAAAAAAAAAAAAoo...................................................................................',
      '.....................ommmmmmmmmmbaaaaaaaaaaAAoo.................................................................................',
      '......................odsssssssssbbbbbbbbbbbbAAoo...............................................................................',
      '.......................odssssssssssllllllllllllwwoo.............................................................................',
      '........................odsssssssssslllllllllllllwwoo...........................................................................',
      '.........................odssssssssssllllllllllllllwwoo.........................................................................',
      '..........................odssssssssssllllllmmlllllllwwoo.......................................................................',
      '...........................odssssssssssllmllllmmlllllllwwoo...............................oooooooooooo..........................',
      '............................odssssssssssllllllllmmlllllllwwoo............................ohhhhhhhchhhho.........................',
      '.............................odsssssssssslllllllllmmmllllllwwoo........................oojjjjggjjcjjjjjoo.......................',
      '.......ooooo............ooooooodsssssssssslllllllllllmmllllllwwooooooooooooooooo......okkkkkgkkkckkkkkkkkoo.....................',
      '..ooooommmmmoooooooooooowwwwwwwwwwwwwwwwwwsllllllllllllmmsssssswwwwwwwwwwwwwwwwwooooookkkkkkkkkkckkkkkkkkkko....................',
      'oommmmmsssssdwwwwwwwwwwwllsllllllllllllllllssssssssssssllmmlllmllllmllslllllllllwwwwwccccccccccccccccccccccco...................',
      'rrrrssssssssdllllmllllllllslmmmmmmmmllllllllllmlslllllllllllmmmmmmllllslllllllllllllcccccccccccccccccccccccco...................',
      'eerrssssssssdlllllllllllllslllllllllllllllllllllslllllllllllllllllllllsllllllllllllllccccccccccccccccccccwwooooo................',
      'eerrssssssssdllllllmllllmmsmmmmmmmmmmmmmmmmmmmmmsmmmmmmmmmmmmmmmmmmmmmsmmmmmmmmmmmmmmmmlllllllllllllllllmllwwwwwooooo...........',
      'eerrssssssssdmmmmmmmmmmmmmsmmmmmmmmmmmmmmmmmmmmmsmmmmmmmmmmmmmmmmmmmmmsmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmyyllllwwwwwooooo......',
      'eerrssssssssdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmmmmmmmAAAwwwwwoo....',
      'rrrrssssssssdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbAAAAAAAaaaAAAAAAwoo..',
      'oossdddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmaaaaaaaaaAAAo.',
      'rrrrssssssssdmmmnnnnnnnnnmnmmmmmmmmmmmmmmmmmmmmmnmnnnnnnnnnnnnnnnnnnmmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmaaabbbbbbooo..',
      'eerrssssssssdmmmnmmmmmmmmmnmmmmmmmssssssssssssssnsnsbbbsbbbsssssssssssnsssssdsdsdsdsdsssssssssssssssssssssssssssssbbbsooooo.....',
      'eerrssssssssdsssnmmmmmmmmsnsssssssssssssssssssssnsnsssssssssssssssssssnsssssdsdsdsdsdssssssssssssssssssddddddddddooooo..........',
      'eerrssssssssdsssssssssssssnsssssssssssssssssssssnsssssssssssssssssssssnssssssssssssssddddddddddddddddddoooooooooo...............',
      'eerrssssssssdsssssssssssssnsssssssssssssssddddddndddddddddddddddddddddndddddddddddddddddddooooooooooooo.........................',
      'rrrrssssssssdsdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddooooooooooooo......................................',
      'ooddddddddddddddddddddmmmmmmmmmmmmmmmmmmmmmmmddoooooooooooooooooooooooooooooo...................................................',
      '..ooooooooooooooooooooosssssssssssssssssssdoooo.................................................................................',
      '......................odssssssssssssssssddo.....................................................................................',
      '.......................odsssssssssssssddoo......................................................................................',
      '........................ossssssssssssdoo........................................................................................',
      '........................odaaaaaaaasddo..........................................................................................',
      '.........................oaaaaaaaadoo...........................................................................................',
      '..........................ooooooooo.............................................................................................',
      '................................................................................................................................',
      '................................................................................................................................',
      '................................................................................................................................',
    ],
    small: [
      '............................................................',
      '...........oooooooooo.......................................',
      '..........ommmmAAAAAAoo.....................................',
      '..........odsssssllllwwoo...................................',
      '...........odssssslllllwwo..................................',
      '............odsssssllmlllwoo..............oooooo............',
      '.............odsssssllmmmlwwoo...........ohhhchho...........',
      '.oooooooooooooodsssslllllmsswwooooooooooojjggcjjjoo.........',
      'ommmmmwwwwwwwwwwwwwwssssssmmwwwwwwwwwwwwkkkkkckkkkko........',
      'rsssssllllllllllllllllllllllllllllllllllkkkkkckkkkoooo......',
      'esssssmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmlllwwwwooo...',
      'esssssAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmAAAwoo.',
      'esssssmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmaabAAAo',
      'rsssssmmmmmmmmmssssssssssssssssssssssssssssssssssssssbboooo.',
      'rsssssssssssssssssssssssssssssssssssssdddddddddddoooooo.....',
      'odddddddddddddddddddddddddddddddddddddooooooooooo...........',
      '.oooooooooommmmmmmmmmooooooooooooooooo......................',
      '..........odssssssdoo.......................................',
      '...........ossssddo.........................................',
      '...........oaaaaoo..........................................',
      '............oooo............................................',
      '............................................................',
    ],
  },
  // Lakon Diamondback Explorer : trapu et taillé à facettes, nez en coin, gros bloc moteur, acier sombre et chevrons rouges.
  dbx: {
    palette: { ...BASE, w: '#c9cdd6', l: '#9aa0b1', m: '#717890', s: '#4c5270', d: '#2f3450', n: '#3b405e', a: '#d8443a', b: '#7e2230', A: '#ff7a5e', p: '#f2c84b', q: '#9a7420' },
    gear: [14, 40, 54],
    lights: [[4,  16,  '#ff4a4a',  0],  [7,  0,  '#eaffff',  0.55]],
    rows: [
      '............ooooooooo...........................................................................................................',
      '......oooooopppppppploo.........................................................................................................',
      '.....ommmmmmmppppppppllooo......................................................................................................',
      '......ossssssssmmmmmmmmllloo....................................................................................................',
      '......odssssssssmmmmmmmmmmllooooooooooo.........................................................................................',
      '.......odssssssssmmmmmmmmmmmllllllllllloo.......................................................................................',
      '........osssllllpssspssspssspsllpmmmmmmlloo.....................................................................................',
      '.......oodssmmmmmpmmmpmmmpmmmpmmmpmmmmmmmlloooo.................................................................................',
      '.oooooommmmmmmmmmpmmmpmmmpmmmpssspsssssssssllwwooooooooooooooo.....................ooooooo......................................',
      'ommmmmmsssssssdssspssspssspsswplllpllllllllllllwwwwwwwwwwwwwwwoooooooooo........ooohhhhhhhooooooo...............................',
      'osssssssssssssdlllllllllllllllslllllmlllllllllllllslllllllllllwwwwwwwwwwoooo.ooojjjjjjggjjcjjjjjjo..............................',
      'rrrsssssssssssdlllllllllllllllslllllllllllllllllllslllllllllllllllllllllwwwwokkkkkkkkkkkgkckkkkkkko.............................',
      'eersssssssssssdlllllllllllllllslllmmmmmmmmmmmmllllslllllllllllllllllllllllllwkkkkkkkkkkkkkkckkkkkkko............................',
      'eersssssssssssdlllllllllllllllslllllllllllllllllllslllllllllllllllllllllllllllllccccccccccccccccccccoo..........................',
      'eersssssssssssdlllllllllllllllslllllllllllllllllllslllllllllllllllllllllllllllmmlllccccccccccccccccccco.........................',
      'rrrsssssssssssdlllllllmlllllllsllmllllllllllllllllsllllllllllllllllllllllllllllllllllmccccccccccccccccco........................',
      'osssssssssssssdmmmmmmmmmmmmmmmsmmmmmmmmmmmmmmmmmmmsmmmmmmmmmmmmmllllllllllllllllllllllllmlcccccccccccccco.......................',
      'rrrsssssssssssdmmmmmmmmmmmmmmmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmmmmlllllllllllllllllllllclccccccccccco......................',
      'eersssssssssssdmmmmmmmmmmmmmmmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAAAmmmmllllllllllllllllllllllwwwooo......................',
      'eersssssssssssdmmmmmmmmmmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaAAAAAAmmmmmllllllllllllllllllwwwooo...................',
      'eersssssssssssdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmbbbbbbbbaaaaAAAAAAmmmmmmllllllllllllllwwwoo.................',
      'rrrsssssssssssdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddmmmmmmmbbbbbbbbaaAAAAAAAmmmmmmllllllllllwwooo..............',
      'osssssssssssssdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmpmpmmmmmxxxxxddddddddddmmmmmbbbbbbbbaAAAAAAmmmmmlllllllwwwooo...........',
      'rrrsssssssssssdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmxxxxdxxxdxxxdxxdddddmmmmmmmmbbbbbbbAAAAAmmmmmmllllwwwooo........',
      'eersssssssssssdmmmmmmmmmmmmmmmnmmmmmmmmmmmmmmmmmmmnmmmmmmmmmmmmmxxxxdxxxdxxxdxxxdxxxmmmmmmmmmmmmmmmmmmmmAAAAAmmmmmmmlwwwooo.....',
      'eersssssssssssdsssssnnnnnnnnssnsssssssssssssssssssnsssssssssssssxxxxdxxxdxxxdxxxdxxxmmmmmmmmmmmmmmmmmmmmmmmmymmmmmmmmmmmlwwo....',
      'eersssssssssssdsssssnmmmmmmmssnsssssssssssssssssssnsssssssssssssxxxxdxxxdxxxdxxxdxxxmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdmmmmo.....',
      'rrrsssssssssssdsssssnmaaaammssnsssssssssssssssssssnsssssssssssssssssdsssdsxxdxxxdxxxsmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmooooo......',
      'osssssssssssssdsssssnmmmmmmmssnsssssssssssssssssssnssssssssssssssssssssssssssssssssssssssssssssmmmmmmmmmmmsdddddooooo...........',
      'osssssssssssssdsssssssssssssssnsssssssssssssssssssnsssssssssssssssssssssssssssssssssssssssssssssssssssdddddooooo................',
      'osssssssssssssddddddddddddddddnddddsssssssssssssssnssssssssssssssssssssssssddddddddddsssssssddddddddddooooo.....................',
      'oddddddsssssssddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddoooooooooo..........................',
      '.ooooooddddddddddddddddddddddddddddddddddddddddddddddddmmmmmmmmmmmmmmddddddooooooooooooooooo....................................',
      '.......ooooooooooooooooooooooodddddddddddmmmmmmmmmmmmmmsssssssssssddooooooo.....................................................',
      '..............................oooooooooooooddssssssssssssssssssssdoo............................................................',
      '...........................................ooddddddddddddddddddddo..............................................................',
      '.............................................oooooooooooooooooooo...............................................................',
      '................................................................................................................................',
      '................................................................................................................................',
      '................................................................................................................................',
    ],
    small: [
      '...oooooooo.................................................',
      '..ommmpppploo...............................................',
      '..odssssmmmlloooooo.........................................',
      '...ossllssssslllllloo.......................................',
      'oooodmssssssssssssslloooooooooooo.....ooooooo...............',
      'mmmmmsswwwwwwwwwwlllwwwwwwwwwwwwwooooohhhhhhho..............',
      'rssssssllllllllllllllllllllllllllwwwjjjjggcjjjo.............',
      'essssssllllllllllllllllllllllllllllllwkkkkckkkko............',
      'esssssslllllllllllllllllllllllllllllllllkkkckkkko...........',
      'essssssmmmmmmmAAAAAAAAAAAAAAAAAmlllllllllllcccccco..........',
      'rssssssmmmmmmmbbbbbbbbbbbbbbbbbAAAAAmmmllllllllwwoo.........',
      'rssssssmmmmmmmmmmmmmmmmmmmmmmmmmmbbbAAAAAAmmmllllwwooo......',
      'essssssmmmmmmmmmmmmmmmmmmmmmmmddddddddmmbbAAAAAmmmlwwwoo....',
      'essssssmmmmmmmmmmmmmmmmmmmmmmmxxxxxxxxdmmmmmmmmmmAAmmmwwo...',
      'esssssssssssssssssssssssssssssxxxxxxxxxmmmmmmmmmmmmmmdddmo..',
      'rssssssssssssssssssssssssssssssssssssssmmmmmmmmmmmmmmoooo...',
      'ssssssssssssssssssssssssssssssssssssssssdddddddddoooo.......',
      'ddddddddddddddddddddddddddddddddddddddddooooooooo...........',
      'oooooooooooooooooddmmmmmmmmmmmmmoooooooo....................',
      '.................oooodddddddddoo............................',
      '.....................ooooooooo..............................',
      '............................................................',
    ],
  },
  // Faulcon DeLacy Krait Phantom : long et fin, cockpit bas tout à l'avant, deux nacelles superposées, bleu nuit et liserés cyan.
  krait: {
    palette: { ...BASE, w: '#dfe8f3', l: '#9fb3cc', m: '#6b80a3', s: '#475a80', d: '#2c3a5c', n: '#36466b', a: '#4fe3e0', b: '#1f8a9c', A: '#b8fff6', p: '#e9edf5', q: '#8a96ad' },
    gear: [14, 36, 52],
    lights: [[3,  15,  '#ff4a4a',  0],  [4,  0,  '#eaffff',  0.55]],
    rows: [
      '......ooooooooo.................................................................................................................',
      '.....oAAAAAAAAAooo..............................................................................................................',
      '......ooaaaaaaaAllooo...........................................................................................................',
      '........ossmmmmmmmlllooo........................................................................................................',
      '.........oosmmmmmmmmmlllooo.....................................................................................................',
      '...........osmmmmmmmmmmmllloo...................................................................................................',
      '............ossmmmmmmmmmmmmllooo................................................................................................',
      '.............oosmmmmmmmmmmmmmlllooo.............................................................................................',
      '...............osmmmmmmmmmmmmmmmlllooo..........................................................................................',
      '..ooooooooooooooosssssssssssssmmmmmlllooo.......................................................................................',
      'oommmmmmmmmmmmmmmmmmmmmmmmmmmmssssssssllloooooooooooooooooooo...................................................................',
      'rrrssssssssssssssssssssssssssssmmmwwwwwwwwwwwwwwwwwwwwmmmmmmmooooooooo..........................................................',
      'eersssssssssssssssssssswwwwwwwwwwwllllllllllllllllllllwwwwwwwwwwwwwwwwooooo.....................................................',
      'eerssssssssswwwwwwwwwwnllmllllllllllllnllllllllllmllllllnlllllllllllllwwwwwooooo................................................',
      'eerssswwwwwwllllllllllnlllllllssssssssssllllllllllllllllnllllllllllllllllllwnwwwooooo.............ooooo.........................',
      'eersssllllllllllllllllnlllllllslllllllnlllllllllllllllllnlllllllllllllllllllnlllwwwwwooooo....oooohhhhhoooooo...................',
      'rrrdddlllllllmllllllllnlllllmlslllllllnlllmlllllllllllllnlllllllllllllllllllnllllllllwwwwwoooojjjjjjjggjjjjjjoooo...............',
      'oooooollllllllllllllllnllllllllllmmmmmnmmmmmmmmmmmmmmmmmnmmmmmmmmlllllllllllnlllllllllllllwwwkkkkkkkkkkkkkkkkkkkko..............',
      '.....ommmmmmmmmmmmmmmmnmmmmmmmmmmmmmmmnmmmmmmmmmmmmmmmmmnmmmmmmmmmmmmmmmmmmmnllllllllllllllllllwkkkkkkkkkkkkkkkkkkoo............',
      '.....ommmmmmmmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaalllllcccccccccccccccccco...........',
      '.....ommmmmmmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaalcccccccccccccccco..........',
      'oooooommmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmbbbaaaaaaamllwwwwwwloooooo.....',
      'rrrlllllllllllllllllllllllllllllllllllllllllllllllllllllmmmmmmmmmmnnnnnnnnnnnnnnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmppppwwwwwywwlooo..',
      'eermmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmsmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmqqqqqqqqqqqqwwwwo.',
      'eermaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaassmmssssssssssssssssssssssssssssmmmmmmmmmmmmmdddddddddddddddoooooooo..',
      'eermmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmssssssmmmssssssssssssssssssssssssssssssssssssssooooooooooooooo..........',
      'eermmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmssssssssssssssssssssssddddddddddddooooooooooooo.........................',
      'eermmmmmnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmmmmmssssssssAsddddddddddddoooooooooooo......................................',
      'eerdddddddddddddddddddddddddddddddddddddddddddddddddddddsssssdddddoooooooooooo..................................................',
      'eerdddddddxdxdxdxdxdxdxdddddddddddddddddddddddddddddddddsssooooooo..............................................................',
      'rrrdddddddddddddddddddddddddddddddddddddddddddddddddddddsoo.....................................................................',
      'ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.......................................................................',
      '................................................................................................................................',
      '................................................................................................................................',
      '................................................................................................................................',
      '................................................................................................................................',
      '................................................................................................................................',
      '................................................................................................................................',
      '................................................................................................................................',
      '................................................................................................................................',
    ],
    small: [
      '....ooooo...................................................',
      '...oAAAAloo.................................................',
      '....osmmmllooo..............................................',
      '.....osmmmmllloo............................................',
      '......osmmmmmmlloo..........................................',
      '.ooooooossssssssllooooooooooo...............................',
      'ommmmmmmmmmmmmwwwwwwwwwwwwwwwooooooo........................',
      'osssswwwwwwwwwlllllllllllllllwwwwwwwoooo......oo............',
      'oddwwlllllllllllllllllllllllllllllllwwwwoooooohhooooo.......',
      '.oollllllllllllllllllmmmmmmmmlllllllllllwwwjjjjggjjjjo......',
      '..ommmmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaallwwkkkkkkkko.....',
      'ooommmmbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaakkkkkkkooo..',
      'rlllllllllllllllllllllllllmmmmmmmmmmmmmmmmmmmmmmmmmmwwwwwwo.',
      'emaaaaaaaaaaaaaaaaaaaaaaaaammssssssssssssssddddddddddddooo..',
      'emmmmmmmmmmmmmmmmmmmmmmmmmsssmmssddddddddddoooooooooooo.....',
      'edddddddddddddddddddddddddsssddddoooooooooo.................',
      'rdddddddddddddddddddddddddsoooooo...........................',
      'roooooooooooooooooooooooooo.................................',
      'o...........................................................',
      '............................................................',
      '............................................................',
      '............................................................',
    ],
  },
  // Lakon Asp Explorer : large et plat, immense verrière panoramique sur le nez, blanc et jaune Lakon.
  asp: {
    palette: { ...BASE, a: '#f2c037', b: '#a07418', A: '#ffe98a', p: '#262b3d', q: '#141824' },
    gear: [14, 38, 52],
    lights: [[5,  17,  '#ff4a4a',  0],  [8,  4,  '#eaffff',  0.55]],
    rows: [
      '................................................................................................................................',
      '................................................................................................................................',
      '................................................................................................................................',
      '................................................................................................................................',
      '................................................................................................................................',
      '................................................................................................................................',
      '.................................oooooooooooooooooooooooooooooo.................................................................',
      '..............ooooooooooooooooooommmmmmmmmmmmmmmmmmmmmmmmmmmmmmo................................................................',
      '.............oAAAAAAAAAAwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwssssssssmoo..............................................................',
      '............oAaaaaaaaaalllpllpllpllllllllllllllllllllllwwsssssssmmoo............................................................',
      '...........oAaaaaaaaaaalllpllpllpllllllllllllllllllllllllwwsssssssmmo...................................oooo....................',
      '..........oAaaaaaaaaaabllllpllpllplllllllllllllllllllllllllwwsssssssmoooooooooooooooooooooooooo......ooohhhhooooo...............',
      '.oooooooooAbbbbbbbbbbbssssspsspsspssssssssssssssssssssssssssswwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwloooooojjjjjjjdjjjjoooo...........',
      'ommmmmmmmdwwwwwwwwwwwwwwswwwwwwwllllllllllllslllllllllllllllllllsllmllmlllllllllllllslllllllllwwwwjjjjjjjjjdggjjjjjjdo..........',
      'rrrrsssssdlllllllllllllmslllllllllmlllllllllslllllllllllllllllllslllllllllllllllllmlsllllllllllljjjjjjjjjjjdjjjjjjjjdjoo........',
      'eerrsssssdllllllllllllllslllllllllllllllllllsllllllllllllmllllllsllllllllllllllmllllsllllllmllllkkkkkkkkkkkdkkkkkkkkdkkko.......',
      'eerrsssssdllllllllllllllsllllllllmllllllllllsllllmllllllllllllllslllllllllllllllllllsllllllllllllkkkkkkkkkkdkkkkkkkkdkkkko......',
      'eerrsssssdllllllllllllllsllllllllmllllllllllslmlllmlllllllllllllslllllllllllllllllllsllllllllllllkkkkkkkkkdkkkkkkkkkdkkkkko.....',
      'eerrsssssdmmmmmmmmmmmmmmsmmmmmmmmmmmmmmmmmmmsmmmmmmmmmmmmmmmmmmmsmmmmmmmmmmmmmmmmmmmsmmmmmmmmmmmmkkkdddddddkkkkkkkkkdkkgkkko....',
      'rrrrsssssdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApAAAApAAAApAAAApAAAApAAAAAAAkkkkkkkkddddddddddddkkkkko....',
      'ossssssssdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaapaaaaapaaapaaaaapaaapaaaaaaaAcccccccdcccccccccdcddddddo...',
      'rrrrsssssdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaapaaaapaaaapaaaapaaaapaaaaaaaAcccccdcccccccccccdccccccco..',
      'eerrsssssdbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbpbbbpbbbbbpbbbpbbbbbpbbbbbbbAccccdcccccccccccdcccccco...',
      'eerrsssssdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmpmmmmpmmmmpmmmmpmmmmpmmmmmmmmccccdcccccccccccdccccco....',
      'eerrsssssdmmmmmmmmmmmmmmnmmmmmnnnnnnnnnnnnmmnmmmmmmmmmmmmmmmmmmmnmmmmmmmmmmmmmmmmmmmnmmmmmmmmmmmmmmmmmcccdcccccccccccdcccoo.....',
      'eerrsssssdssssssssssssssnsssssnmmmmmmmmmmmssnsssdsdsdsdsdsdsssssnsssssssssssssssssssnsssssmmmmmmmmmmmmmcdccccccccccccdcco.......',
      'rrrrsssssdssssssssssssssnsssssnmaaamaaammmssnsssdsdsdsdsdsdsssssnsssssssssssssssssssnsssssssssssssssssssdssssssccccccdco........',
      'ossssssssdssssssssssssssnsssssnmmmmmmmmmmmssnsssssssssssssssssssnsssssssssssssssssssnsssssssyysssssssssssssssddsssdddoo.........',
      'ossssssssdssssssssssssssnsssssssssssssssssssnsssssssssssssssssssnsssssssssssssssssssnsssssssssssdddddddddddddoooooooo...........',
      'odddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmsssssssssssssssssssssssssssssdddddddddddddddddddddddddddddddooooooooooooo...................',
      '.oooooooooodssssssssssssssssssssssssmmmmmmmmmmmmmmmmmmmmmmmmmddddooooooooooooooooooooooooooooooo................................',
      '...........odsssssssssssssssnnnnnnnnnnnnnnsssssssssssssssddoooooo...............................................................',
      '............odsssssssssssssssssssssssssssssssssssssssssddoo.....................................................................',
      '.............odssssssssssssssssssssssssssssssssssssssddoo.......................................................................',
      '..............oddddddddddddddddddddddddddddddddddddddoo.........................................................................',
      '...............oooooooooooooooooooooooooooooooooooooo...........................................................................',
      '................................................................................................................................',
      '................................................................................................................................',
      '................................................................................................................................',
      '................................................................................................................................',
    ],
    small: [
      '............................................................',
      '............................................................',
      '............................................................',
      '......oooooooooooooooooooooooo..............................',
      '.....oAAAAAwwwwwwwwwwwwwwmmmmmo.............................',
      '.....oaaaaallllllllllllllwwsssmoo...............oooo........',
      'oooooAbbbbbsssssssssssssssswwddmmooooooooooooooohhhdooo.....',
      'mmmmwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwjjjjjdjjdo....',
      'rsssllllllllllllllllllllllllllllllllllllllllljjjjjdjjjdjo...',
      'essslllllllllllllllllllllllllllllllllllllllllljjjjdjjjdjjo..',
      'esssAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkddddddkdkgko.',
      'esssaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAkkkdkkdddddo.',
      'esssbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbAkkdkkkkdkko.',
      'rsssmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmkdkkkkkdko..',
      'rssssssssssssssssssssssssssssssssssssssssssssssssdskkkkdo...',
      'ddddssssssssssssssssssssssssssssssssssssssddddddddddsooo....',
      'oodddmmmmmmmmmmmmmmmmmmmmmmmmdddddddddddddooooooooooo.......',
      '..oooodsssssssssssssssssssdooooooooooooooo..................',
      '......odddddddddddddddddddo.................................',
      '.......ooooooooooooooooooo..................................',
      '............................................................',
      '............................................................',
    ],
  },
};
