name: PREPROD - Déploiement FTP

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ftp-deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Envoyer le site sur le FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_URL }}
          username: ${{ secrets.FTP_LOGIN }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./preprod-it-s-dangerous-out-there/
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            README.md
            logo-gg.html
